mysite/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
    url(r'^polls/', include('polls.urls', namespace="polls")),
    url(r'^spotify_app/', include('spotify_app.urls', namespace="spotify_app")),
    url(r'^admin/', include(admin.site.urls)),
)

polls/urls.py
from django.conf.urls import patterns, url

from polls import views

urlpatterns = patterns('',
    # ex: /polls/
    url(r'^$', views.index, name='index'),
    # ex: /polls/5/
    url(r'^(?P<question_id>\d+)/$', views.detail, name='detail'),
    # ex: /polls/5/results/
    url(r'^(?P<question_id>\d+)/results/$', views.results, name='results'),
    # ex: /polls/5/vote/
    url(r'^(?P<question_id>\d+)/vote/$', views.vote, name='vote'),
)

spotify_app/urls.py
from django.conf.urls import patterns, url

from spotify_app import views

urlpatterns = patterns('',
    # ex: /polls/5/
    url(r'^login/$', views.login, name='login'),
    url(r'^do_login/$', views.do_login, name='do_login'),
    url(r'^logout/$', views.logout, name='logout'),
    url(r'^search/$', views.search, name='search'),
    url(r'^play/(?P<track_id>spotify:track:[0-9a-zA-Z]+)/$', views.play, name='play'),
    url(r'^remove_from_queue/(?P<queue_id>\d+)$', views.remove_from_queue, name='remove_from_queue'),
    url(r'^playlist/$', views.playlist, name='playlist'),
    url(r'^play_next/$', views.play_next, name='play_next'),
    url(r'^play_prev/$', views.play_prev, name='play_prev'),
    url(r'^set_audio_output/(?P<output>\d)$', views.set_audio_output, name='set_audio_output'),
    url(r'^set_volume/$', views.set_volume, name='set_volume'),
)

polls/models.py
import datetime

from django.db import models
from django.utils import timezone


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    
    def __str__(self):
        return self.question_text
        
    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)
    
    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published recently?'

class Choice(models.Model):
    question = models.ForeignKey(Question)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    
    def __str__(self):
        return self.choice_text

spotify_app/models.py
from django.db import models

# Create your models here.

polls/views.py
from django.http import HttpResponse, Http404
from django.shortcuts import render, get_object_or_404

from polls.models import Question

def index(request):
    latest_question_list = Question.objects.order_by('-pub_date')[:5]
    context = {'latest_question_list': latest_question_list}
    return render(request, 'polls/index.html', context)
    
def detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/detail.html', {'question': question})

def results(request, question_id):
    response = "You're looking at the results of question %s."
    return HttpResponse(response % question_id)

def vote(request, question_id):
    return HttpResponse("You're voting on question %s." % question_id)

spotify_app/views.py
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.shortcuts import render, get_object_or_404
from django.core.urlresolvers import reverse

from spotify_app.player import Player

p = Player();
current_search = []

def playlist(request):
    global p
    context = {'playlist': p.get_playlist()}
    return render(request, 'spotify_app/playlist.html', context)

current_track = None

def play(request, track_id):
    global p
    global current_search
    if p.is_playing():
        p.queue(track_id)
    else:
        p.play(track_id)
    
    context = {'tracks': current_search, 'playlist': p.get_playlist(), "current_volume": p.get_volume()}
    return render(request, 'spotify_app/search.html', context)
    
def remove_from_queue(request, queue_id):
    global p
    p.remove_from_queue(queue_id)
    context = {'tracks': current_search, 'playlist': p.get_playlist(), "current_volume": p.get_volume()}
    return render(request, 'spotify_app/search.html', context)
    
def play_prev(request):
    global p
    p.play_prev()
    context = {'tracks': current_search, 'playlist': p.get_playlist(), "current_volume": p.get_volume()}
    return render(request, 'spotify_app/search.html', context)
    
def play_next(request):
    global p
    p.play_next()
    context = {'tracks': current_search, 'playlist': p.get_playlist(), "current_volume": p.get_volume()}
    return render(request, 'spotify_app/search.html', context)

def set_audio_output(request, output):
    global p
    p.set_audio_output(output)
    context = {'tracks': current_search, 'playlist': p.get_playlist(), "current_volume": p.get_volume()}
    return render(request, 'spotify_app/search.html', context)
   
def set_volume(request):
    global p
    p.set_volume(request.POST['volume'])
    context = {'tracks': current_search, 'playlist': p.get_playlist(), "current_volume": p.get_volume()}
    return render(request, 'spotify_app/search.html', context)
    
def login(request):
    return render(request, 'spotify_app/login.html')
    
def do_login(request):
    global p
    p.login(request.POST['username'], request.POST['password'])
    tracks = []
    return render(request, 'spotify_app/search.html', tracks)
    
def logout(request):
    global p
    p.logout()
    return render(request, 'spotify_app/login.html')
    
def search(request):
    global p
    global current_search
    current_search = p.search(request.POST.get('query', 'björnstammen'))
    context = {'tracks': current_search, 'playlist': p.get_playlist(), "current_volume": p.get_volume()}
    return render(request, 'spotify_app/search.html', context)

polls/templates/polls/detail.html
<h1>{{ question.question_text }}</h1>
<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }}</li>
{% endfor %}
</ul>

polls/templates/polls/index.html
{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

spotify_app/templates/spotify_app/login.html
<h1>Logga in</h1>

<form action="{% url 'spotify_app:do_login' %}" method="post">
{% csrf_token %}
    <input type="text" name="username" id="username" value="c.gunning" /><br />
    <input type="text" name="password" id="password" value="" /><br />
<input type="submit" value="Logga in" />
</form>

spotify_app/templates/spotify_app/playlist.html
<ul>
{% for track in playlist %}
    <li><a href="{% url 'spotify_app:remove_from_queue' queue_id=forloop.counter0 %}">{{ track.name }}</a></li>
{% endfor %}
</ul>

spotify_app/templates/spotify_app/search.html
<script>
function myFunction() {
    document.getElementById("volume-form").submit();
    console.log(document.getElementById("volume").value)
}
</script>

<h1>Sök</h1>
<a href="{% url 'spotify_app:set_audio_output' '2' %}">HDMI</a> <a href="{% url 'spotify_app:set_audio_output' '1' %}">3.5 mm</a><br />
<a href="{% url 'spotify_app:play_prev' %}">Spela förra</a> <a href="{% url 'spotify_app:play_next' %}">Spela nästa</a>

<form action="{% url 'spotify_app:search' %}" method="post">
{% csrf_token %}
    <input type="text" name="query" id="query" value="" /><br />
    <input type="submit" value="Sök" />
</form>
<form action="{% url 'spotify_app:set_volume' %}" method="post" id="volume-form">
{% csrf_token %}
    <input type="range" name="volume" id="volume" min="70" max="100" value="{{ current_volume }}" onchange="myFunction()" /><br />
</form>

<div style="float: left; padding-right: 20px;">
    <h3>Results</h3>
    <ul>
    {% for track in tracks %}
        <li><a href="{% url 'spotify_app:play' track_id=track.link.uri %}">{{ track.name }}</a></li>
    {% endfor %}
    </ul>
</div>

<div style="float: left;">
    <h3>Queue</h3>
    <ul>
    {% for track in playlist %}
        <li><a href="{% url 'spotify_app:remove_from_queue' queue_id=forloop.counter0 %}">{{ track.name }}</a></li>
    {% endfor %}
    </ul>
</div>